version: '3.8'


services:
  app1:
    build: .
    image: app1
    container_name: app1
    ports:
      - 6004:5000
    command: python manage_object.py run -h 0.0.0.0 --no-debugger
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_APP=object_repo/__init__.py
    depends_on:
      - web
  app2:
    build: .
    image: app2
    container_name: app2
    ports:
      - 6005:5000
    command: python manage_object.py run -h 0.0.0.0 --no-debugger
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_APP=object_repo/__init__.py
    depends_on:
      - web
  web:
    build: .
    image: web
    container_name: web
    ports:
      - 5004:5000
    command: ./run_server.sh
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.dev
    depends_on:
      - db
      - mongodb
      - redis
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
  
  dashboard:
    build: .
    command: celery flower -A project.celery --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://hello_flask:hello_flask@db:5432/hello_flask_dev
    depends_on:
      - web
      - redis


  redis:
    image: redis:6-alpine

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod #--auth
    environment:
      - MONGO_INITDB_DATABASE=flaskdb
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes:
      - mongodbdata:/data/db
volumes:
  postgres_data:
  mongodbdata:
