{
 "title": "Druidnet",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "γ parameter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_rate_flavor_small", "legendFormat": "γ for flavor_small" },
    { "expr": "process_rate_flavor_medium", "legendFormat": "γ for flavor_medium" },
    { "expr": "process_rate_flavor_big", "legendFormat": "γ for flavor_big" },
    { "expr": "replicas_flavor_small", "legendFormat": "replicas flavor_small" },
    { "expr": "replicas_flavor_medium", "legendFormat": "replicas flavor_medium" },
    { "expr": "replicas_flavor_big", "legendFormat": "replicas flavor_big" }
   ]
  },
  {
   "title": "Number of pods",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_replicaset_status_replicas{replicaset=~\"flavor.*\"})",
     "legendFormat": "Total pods on apps"
    },
    {
     "expr": "kube_replicaset_status_replicas{replicaset=~\"flavor-small.*\"}",
     "legendFormat": "total flavor_small"
    },
    {
     "expr": "kube_replicaset_status_replicas{replicaset=~\"flavor-medium.*\"}",
     "legendFormat": "total flavor_medium"
    },
    {
     "expr": "kube_replicaset_status_replicas{replicaset=~\"flavor-big.*\"}",
     "legendFormat": "total flavor_big"
    },
    { "expr": "replicas_flavor_small", "legendFormat": "replicas_flavor_small" },
    { "expr": "replicas_flavor_medium", "legendFormat": "replicas_flavor_medium" },
    { "expr": "replicas_flavor_big", "legendFormat": "replicas_flavor_big" }
   ]
  },
  {
   "title": "Tasks Not Finished",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "active_requests_flavor_small", "legendFormat": "active_requests_flavor_small" },
    { "expr": "active_requests_flavor_medium", "legendFormat": "active_requests_flavor_medium" },
    { "expr": "active_requests_flavor_big", "legendFormat": "active_requests_flavor_big" }
   ]
  },
  {
   "title": "Processing time",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_sum{service=~\"flavor.*\"} [10s])\n    ) /\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_count{service=~\"flavor.*\"} [10s])\n    )\n)",
     "legendFormat": "Total Average processing rate "
    },
    {
     "expr": "avg_over_time(average_response_time [30s])",
     "legendFormat": "average response 30s"
    },
    { "expr": "average_response_time", "legendFormat": "average response time per sec" },
    {
     "expr": "avg by (service) (\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_sum{service=~\"flavor-small.*\"} [10s])\n    ) /\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_count{service=~\"flavor-small.*\"} [10s])\n    )\n)",
     "legendFormat": "average processing time flavor_small per 10sec"
    },
    {
     "expr": "avg by (service) (\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_sum{service=~\"flavor-medium\"} [10s])\n    ) /\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_count{service=~\"flavor-medium\"} [10s])\n    )\n)",
     "legendFormat": "average processing time flavor_medium per 10sec"
    },
    {
     "expr": "avg by (service) (\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_sum{service=~\"flavor-big\"} [10s])\n    ) /\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_count{service=~\"flavor-big\"} [10s])\n    )\n)",
     "legendFormat": "average processing time flavor_big per 10sec"
    },
    {
     "expr": "sum(avg_over_time(average_response_time [10s])) - avg(sum by (pod) (\n      rate(flask_http_request_duration_seconds_sum{service=~\"flavor.*\"} [10s])\n    ) /\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_count{service=~\"flavor.*\"} [10s])\n    )\n)",
     "legendFormat": "Total Average Queuing Time (per 10sec)"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "queue_size", "legendFormat": "Queue size" },
    { "expr": "req_rate_flavor_small", "legendFormat": "Request_Rate_flavor_small" },
    { "expr": "req_rate_flavor_medium", "legendFormat": "Request_Rate_flavor_medium" },
    { "expr": "req_rate_flavor_big", "legendFormat": "Request_Rate_flavor_big" }
   ]
  },
  {
   "title": "CPU cores ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"flavor-small.*\"} [1m]))  by (container) ",
     "legendFormat": "Total cores flavor_small"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"flavor-medium.*\"} [1m])) by (container) ",
     "legendFormat": "Total cores flavor_medium"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"flavor-big.*\"} [1m])) by (container) ",
     "legendFormat": "Total cores flavor_big"
    },
    {
     "expr": "sum by (service)(kube_pod_container_resource_limits{pod=~\"flavor-small.*\",resource=\"cpu\"})",
     "legendFormat": "limits for flavor_small service"
    },
    {
     "expr": "sum by (service)(kube_pod_container_resource_limits{pod=~\"flavor-medium.*\",resource=\"cpu\"})",
     "legendFormat": "limits for flavor_medium service"
    },
    {
     "expr": "sum by (service)(kube_pod_container_resource_limits{pod=~\"flavor-big.*\",resource=\"cpu\"})",
     "legendFormat": "limits for flavor_big service"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"flavor-.*\",resource=\"cpu\"})",
     "legendFormat": "Total CPU resources"
    }
   ]
  },
  {
   "title": "Finished Requests rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(flask_http_request_total{service=~\".*flavor.*\"} [10s]))",
     "legendFormat": "Average Rate per 10s"
    },
    {
     "expr": "sum by (service) (\n  sum by (pod, status) (\n    rate(flask_http_request_total{service=~\".*flavor-small*\"} [10s])\n  )\n)",
     "legendFormat": "{{pod}} Rate per 10s for flavor_small "
    },
    {
     "expr": "sum by (service) (\n  sum by (pod, status) (\n    rate(flask_http_request_total{service=~\".*flavor-medium*\"} [10s])\n  )\n)",
     "legendFormat": "{{pod}} Rate per 10s for flavor_medium"
    },
    {
     "expr": "sum by (service) (\n  sum by (pod, status) (\n    rate(flask_http_request_total{service=~\".*flavor-big*\"} [10s])\n  )\n)",
     "legendFormat": "{{pod}} Rate per 10s for flavor_big"
    },
    {
     "expr": "sum (rate(flask_http_request_total{service=~\".*web.*\"} [10s]))",
     "legendFormat": "Controller Rate per 10s"
    }
   ]
  },
  {
   "title": "CPU Utilization % ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"flavor.*\"}[1m])) by (pod_name, container_name) /\nsum(container_spec_cpu_quota{container=~\"flavor.*\"}/container_spec_cpu_period{container=~\"flavor.*\"}) by (pod_name, container_name)*100",
     "legendFormat": "Total CPU usage as a  % of limit"
    },
    {
     "expr": "sum by (service) (rate(container_cpu_cfs_throttled_seconds_total{container=~\"flavor-small.*\"}[1m]))",
     "legendFormat": "Total cpu throttling flavor_small in seconds"
    },
    {
     "expr": "sum by (service) (rate(container_cpu_cfs_throttled_seconds_total{container=~\"flavor-medium.*\"}[1m]))",
     "legendFormat": "Total cpu throttling flavor_medium in seconds"
    },
    {
     "expr": "sum by (service) (rate(container_cpu_cfs_throttled_seconds_total{container=~\"flavor-big.*\"}[1m]))",
     "legendFormat": "Total cpu throttling flavor_big in seconds"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"flavor-small.*\"}[1m])) by (pod_name, container_name) /\nsum(container_spec_cpu_quota{container=~\"flavor-small.*\"}/container_spec_cpu_period{container=~\"flavor-small.*\"}) by (pod_name, container_name)*100",
     "legendFormat": "Total CPU usage for flavor_small as a  % of limit"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"flavor-medium.*\"}[1m])) by (pod_name, container_name) /\nsum(container_spec_cpu_quota{container=~\"flavor-medium.*\"}/container_spec_cpu_period{container=~\"flavor-medium.*\"}) by (pod_name, container_name)*100",
     "legendFormat": "Total CPU usage for flavor_medium as a  % of limit"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"flavor-big.*\"}[1m])) by (pod_name, container_name) /\nsum(container_spec_cpu_quota{container=~\"flavor-big.*\"}/container_spec_cpu_period{container=~\"flavor-big.*\"}) by (pod_name, container_name)*100",
     "legendFormat": "Total CPU usage for flavor_big as a  % of limit"
    },
    { "expr": "100" }
   ]
  },
  {
   "title": "Started Requests Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "rate(flower_events_total{type=\"task-received\",worker=\"celery@flavor_small_worker\"}[10s])",
     "legendFormat": "flavor_medium worker"
    },
    {
     "expr": "rate(flower_events_total{type=\"task-received\",worker=\"celery@flavor_medium_worker\"}[10s])",
     "legendFormat": "flavor_medium worker"
    },
    {
     "expr": "rate(flower_events_total{type=\"task-received\",worker=\"celery@flavor_big_worker\"}[10s])",
     "legendFormat": "flavor_big worker"
    },
    {
     "expr": "rate(flower_events_total{type=\"task-received\",worker=\"celery@queue_worker\"}[10s])",
     "legendFormat": "queue worker"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=~\"flavor.*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (service)(container_memory_usage_bytes{container=~\"flavor-small.*\"})",
     "legendFormat": "Total Memory Usage service flavor_small"
    },
    {
     "expr": "sum by (service)(container_memory_usage_bytes{container=~\"flavor-medium.*\"})",
     "legendFormat": "Total  Memory Usage service flavor_medium"
    },
    {
     "expr": "sum by (service)(container_memory_usage_bytes{container=~\"flavor-big.*\"})",
     "legendFormat": "Total  Memory Usage service flavor_big"
    },
    {
     "expr": "sum by (service)(container_spec_memory_limit_bytes{pod=~\"flavor-small.*\"})\n",
     "legendFormat": "Memory Limit Pod flavor_small"
    },
    {
     "expr": "sum by (service)(container_spec_memory_limit_bytes{pod=~\"flavor_medium.*\"})\n",
     "legendFormat": "Memory Limit Pod flavor_medium"
    },
    {
     "expr": "sum by (service)(container_spec_memory_limit_bytes{pod=~\"flavor_big.*\"})\n",
     "legendFormat": "Memory Limit Pod flavor_big"
    }
   ]
  },
  {
   "title": "Total Number of Requests per Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(flask_http_request_total{service=~\"flavor.*\"} [30s])))",
     "legendFormat": "Total on apps"
    },
    {
     "expr": "round(sum(increase(flask_http_request_total{service=~\"web.*\",status=\"202\"} [30s])))",
     "legendFormat": "Total on controller"
    }
   ]
  }
 ]
}