apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue
spec:
  scaleTargetRef:
    name: app1
  pollingInterval: 1
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-k8s.monitoring.svc.cluster.local:9090
      metricName: queue_trigger
      threshold: '2'
      query: (sum(queue_trigger))

