apiVersion: apps/v1 
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - args:
            - ./run_server.sh
          env:
            - name: APP1_IP
              valueFrom:
                configMapKeyRef:
                  key: APP1_IP
                  name: env-dev
            - name: APP2_IP
              valueFrom:
                configMapKeyRef:
                  key: APP2_IP
                  name: env-dev
            - name: APP_SETTINGS
              valueFrom:
                configMapKeyRef:
                  key: APP_SETTINGS
                  name: env-dev
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  key: CELERY_BROKER_URL
                  name: env-dev
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                configMapKeyRef:
                  key: CELERY_RESULT_BACKEND
                  name: env-dev
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DATABASE
                  name: env-dev
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: env-dev
            - name: FLASK_APP
              valueFrom:
                configMapKeyRef:
                  key: FLASK_APP
                  name: env-dev
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env-dev
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-dev
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env-dev
            - name: SQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: SQL_HOST
                  name: env-dev
            - name: SQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: SQL_PORT
                  name: env-dev
            - name: CELERY_BEAT
              value: "1"
            - name: beta1
              value: "0.7"
            - name: beta2
              value: "0.7"
            - name: alpha1
              value: "0.1"
            - name: alpha2
              value: "0.2"
            - name: event_cooldown
              value: '0'
            - name: PROMETHEUS_MULTIPROC_DIR
              value: '/tmp'
          image: dspatharakis/controller_druidnet:web
          name: web
          resources:
            limits:
              cpu: "4000m"
              memory: "8Gi"
            requests:
              cpu: "4000m"
              memory: "8Gi"
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
